name: testing
on:
  pull_request:
    branches:
      - main
      - master
jobs:
  test-code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7.13
      - name: Caching
        uses: actions/cache@v2
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ env.pythonLocation }}-${{ hashFiles('setup.py') }}
      - name: Install dependencies
        run: |
          python -m pip install -e ".[test]" --no-cache-dir
      - name: Execute tests
        run: pytest -v test/